### ISSUE TITLE
dynimcally added markers are clustered despite disableClustering

### ISSUE THREAD

**Issue by siegfriedo** [ghybs/Leaflet.MarkerCluster.Freezable#1]
Hello ghybs,

thanks for your work.

I' am using your plugin to enable or disable Clustering in my project (with the latest source code of leaflet, markercluster and freezable). Well, it works fine unless Clustering is disabled and markers will be added afterwards. Those makers will be always clustered.
Updateing the map, for example moving, does partly solve the problem. It will be shown correctly disabled if I enable and disable Clustering again.

I wrote a similar example, as I am using in my project in jsfiddle, with a bit older source but with the same issue:
http://jsfiddle.net/tdj6gmbf/5/
Uncheck "Clustering" and then "Add"

Am I doing something wrong or is this a bug?

**Comment by ghybs** [comment]
Hi,

Thank you for your feedback!

Mmm indeed I have not considered the usage of adding / removing markers while MCG is frozen.
But it is a valid use case for sure!

Thank you for the JSFiddle that shows the problem!
Looks like a "bug" indeed, but unfortunately it is somehow on Leaflet.markercluster side in `addLayer` method: it reads the [current map zoom](https://github.com/Leaflet/Leaflet.markercluster/blob/v0.5.0/src/MarkerClusterGroup.js#L113) instead of using its internal `_zoom` value, which is what MCG.Freezable plugin uses to force a freeze.

It is not a "bug" _per se_ for MCG alone, as `this._zoom` should not be different from `this._map.getZoom()` in almost all cases (maybe except while changing zoom, but this should be a very transient situation into which I doubt an `addLayer` could be executed - I do not recall any async operation except animation).
Except when used with MCG.Freezable plugin, where indeed the 2 differ…

I have updated the JSFiddle with a "workaround" that overrides `addLayer` to read `this._zoom` instead of `this._map.getZoom()`: http://jsfiddle.net/tdj6gmbf/6/
It looks to me that it solves your problem, please can you confirm?

It could be tempting to include this `addLayer` override in MCG.Freezable, but that would open the door to mismatch with MCG should it evolve on this core API method.
For instance, `addLayer` in [`master`](https://github.com/Leaflet/Leaflet.markercluster/blob/v1.0.0-rc.1/src/MarkerClusterGroup.js#L74-L124) branch (compatible with Leaflet 1.0) and in [`leaflet-0.7`](https://github.com/Leaflet/Leaflet.markercluster/blob/v0.5.0/src/MarkerClusterGroup.js#L74-L128) branch already differ!

As for removing layers, it looks like MCG does not read the map zoom, so there should not be any similar bug.

Please can you confirm if the above workaround solves your issue?

**Comment by siegfriedo** [comment]
It works, thank you.

Changing
`currentZoom = this._map.getZoom();`
to
`currentZoom = this._zoom;`
solved it.

If it helps you, I am currently using leaflet-1.0.0-rc.2, freezable 0.1.0 and markercluster, I guess the latest version. The only other small difference for `addLayer` is:
https://github.com/Leaflet/Leaflet.markercluster/blob/v1.0.0-rc.1/src/MarkerClusterGroup.js#L76-L78
https://github.com/Leaflet/Leaflet.markercluster/blob/v0.5.0/src/MarkerClusterGroup.js#L76-L82
