### ISSUE TITLE
bower package

### ISSUE THREAD

**Issue by HamzaJridi** [ghybs/Leaflet.MarkerCluster.Freezable#4]
I use a bower package for leaflet and leafler.MarkerCluster, so when I add "<script src="leaflet.markercluster.freezable.js"></script>" to my index.html file it throws an error, I think it's due to that the "Leaflet.MarkerCluster.Freezable" library is loaded before the others.
Is ther a bower package for "Leaflet.MarkerCluster.Freezable" ?

**Comment by ghybs** [comment]
Hi,

Thank you for your message!

Sorry I do not use Bower, so I do not know what a bower package looks like nor how to make one.
Please feel free to submit a PR, if possible referencing how to make and maintain the package definition file, so that other people (including me if necessary) can maintain it.

As a workaround, you could also dynamically load the `<script>` tag at the appropriate moment, i.e. after Leaflet and Leaflet.markercluster scripts have been loaded by Bower.

Hope this helps.

**Comment by HamzaJridi** [comment]
I've found a bower package for this library https://libraries.io/bower/leaflet.markercluster.freezable.keeprock

I don't know if you know [npm](https://www.npmjs.com/) (node package manager), [bower](https://bower.io/) is a package manager for the frontend.
